name: Check for new release of NVR

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Wiki
        uses: actions/checkout@v4
      - name: Get branch of the latest NVR commit
        run: |
          echo "NVR_BRANCH=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/pr0bability/TESReloaded10/events | jq -r '.[0].payload.ref' | cut -d "/" -f 3)" >> $GITHUB_ENV
      - name: Get NVR toml 
        run: |
          curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/pr0bability/TESReloaded10/contents/resource/NewVegasReloaded.dll.defaults.toml?ref=${{ env.NVR_BRANCH }} | jq -r '.download_url' | xargs -n 1 curl -O
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: npm
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Install dependencies
        run: npm ci
      - name: Parse NVR toml and convert into Markup 
        run: npm run parse
      - name: Build website
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: dlpnd
          user_email: dark0lord@yandex.ru
